services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: pms_postgres
    environment:
      POSTGRES_DB: permit_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "${POSTGRES_HOST_PORT:-15432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: pms_server
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/permit_manager
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      PORT: 5000
      CLIENT_URL: http://localhost:3000
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 10485760
      ALLOWED_FILE_TYPES: pdf,doc,docx,xls,xlsx,jpg,jpeg,png
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pms_network
    working_dir: /app
    command: npm run dev
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: pms_client
    environment:
      REACT_APP_API_URL: http://server:5000/api
      REACT_APP_VERSION: ${REACT_APP_VERSION:-1.0.0}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      GENERATE_SOURCEMAP: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - pms_network
    working_dir: /app
    command: npm start
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local

networks:
  pms_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
